/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'storeNumber' : IDL.Text,
  'gstNumber' : IDL.Text,
  'userId' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'rate' : IDL.Float64,
  'unit' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'quantity' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'deliveredAt' : IDL.Opt(Time),
  'storeNumber' : IDL.Text,
  'createdAt' : Time,
  'invoiceNumber' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'customerId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'cheque' : IDL.Null,
  'online' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'referenceNumber' : IDL.Text,
  'storeNumber' : IDL.Text,
  'recordedAt' : Time,
  'notes' : IDL.Text,
  'companyName' : IDL.Text,
  'customerId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'rate' : IDL.Float64,
  'unit' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Opt(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'customerId' : IDL.Opt(IDL.Text),
});
export const CompanyProfile = IDL.Record({
  'bankAccountNumber' : IDL.Text,
  'contact' : IDL.Text,
  'adminPasswordHash' : IDL.Text,
  'ifscCode' : IDL.Text,
  'gstNumber' : IDL.Text,
  'email' : IDL.Text,
  'bankName' : IDL.Text,
  'appVersion' : IDL.Text,
  'logoUrl' : IDL.Opt(ExternalBlob),
  'adminUserId' : IDL.Text,
  'signatureUrl' : IDL.Opt(ExternalBlob),
  'address' : IDL.Text,
  'upiQrImageUrl' : IDL.Opt(ExternalBlob),
  'upiId' : IDL.Text,
  'companyName' : IDL.Text,
  'bankAccountName' : IDL.Text,
  'branchName' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'todayRevenue' : IDL.Float64,
  'totalRevenue' : IDL.Float64,
  'totalCustomers' : IDL.Nat,
  'todayOrders' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([Customer], [], []),
  'addOrder' : IDL.Func([Order], [], []),
  'addPayment' : IDL.Func([Payment], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkImportProducts' : IDL.Func([IDL.Vec(Product)], [], []),
  'bulkToggleProducts' : IDL.Func([IDL.Bool], [], []),
  'deleteCustomer' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'editCustomer' : IDL.Func([IDL.Text, Customer], [], []),
  'editProduct' : IDL.Func([IDL.Text, Product], [], []),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyProfile' : IDL.Func([], [IDL.Opt(CompanyProfile)], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getOrdersByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getPaymentsByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleCustomerState' : IDL.Func([IDL.Text], [], []),
  'toggleProductState' : IDL.Func([IDL.Text], [], []),
  'updateCompanyProfile' : IDL.Func([CompanyProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'storeNumber' : IDL.Text,
    'gstNumber' : IDL.Text,
    'userId' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'rate' : IDL.Float64,
    'unit' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'quantity' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'deliveredAt' : IDL.Opt(Time),
    'storeNumber' : IDL.Text,
    'createdAt' : Time,
    'invoiceNumber' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'customerId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const PaymentMethod = IDL.Variant({
    'cash' : IDL.Null,
    'cheque' : IDL.Null,
    'online' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'referenceNumber' : IDL.Text,
    'storeNumber' : IDL.Text,
    'recordedAt' : Time,
    'notes' : IDL.Text,
    'companyName' : IDL.Text,
    'customerId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'rate' : IDL.Float64,
    'unit' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Opt(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'customerId' : IDL.Opt(IDL.Text),
  });
  const CompanyProfile = IDL.Record({
    'bankAccountNumber' : IDL.Text,
    'contact' : IDL.Text,
    'adminPasswordHash' : IDL.Text,
    'ifscCode' : IDL.Text,
    'gstNumber' : IDL.Text,
    'email' : IDL.Text,
    'bankName' : IDL.Text,
    'appVersion' : IDL.Text,
    'logoUrl' : IDL.Opt(ExternalBlob),
    'adminUserId' : IDL.Text,
    'signatureUrl' : IDL.Opt(ExternalBlob),
    'address' : IDL.Text,
    'upiQrImageUrl' : IDL.Opt(ExternalBlob),
    'upiId' : IDL.Text,
    'companyName' : IDL.Text,
    'bankAccountName' : IDL.Text,
    'branchName' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'todayRevenue' : IDL.Float64,
    'totalRevenue' : IDL.Float64,
    'totalCustomers' : IDL.Nat,
    'todayOrders' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([Customer], [], []),
    'addOrder' : IDL.Func([Order], [], []),
    'addPayment' : IDL.Func([Payment], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkImportProducts' : IDL.Func([IDL.Vec(Product)], [], []),
    'bulkToggleProducts' : IDL.Func([IDL.Bool], [], []),
    'deleteCustomer' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'editCustomer' : IDL.Func([IDL.Text, Customer], [], []),
    'editProduct' : IDL.Func([IDL.Text, Product], [], []),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyProfile' : IDL.Func([], [IDL.Opt(CompanyProfile)], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getOrdersByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getPaymentsByCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleCustomerState' : IDL.Func([IDL.Text], [], []),
    'toggleProductState' : IDL.Func([IDL.Text], [], []),
    'updateCompanyProfile' : IDL.Func([CompanyProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };