/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanyProfile {
  'bankAccountNumber' : string,
  'contact' : string,
  'adminPasswordHash' : string,
  'ifscCode' : string,
  'gstNumber' : string,
  'email' : string,
  'bankName' : string,
  'appVersion' : string,
  'logoUrl' : [] | [ExternalBlob],
  'adminUserId' : string,
  'signatureUrl' : [] | [ExternalBlob],
  'address' : string,
  'upiQrImageUrl' : [] | [ExternalBlob],
  'upiId' : string,
  'companyName' : string,
  'bankAccountName' : string,
  'branchName' : string,
}
export interface Customer {
  'id' : string,
  'customerName' : string,
  'storeNumber' : string,
  'gstNumber' : string,
  'userId' : [] | [string],
  'createdAt' : Time,
  'isActive' : boolean,
  'email' : string,
  'address' : string,
  'companyName' : string,
  'passwordHash' : string,
  'phone' : string,
}
export interface DashboardStats {
  'totalProducts' : bigint,
  'totalOrders' : bigint,
  'todayRevenue' : number,
  'totalRevenue' : number,
  'totalCustomers' : bigint,
  'todayOrders' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'deliveredAt' : [] | [Time],
  'storeNumber' : string,
  'createdAt' : Time,
  'invoiceNumber' : string,
  'totalAmount' : number,
  'address' : string,
  'companyName' : string,
  'customerId' : string,
  'items' : Array<OrderItem>,
  'isDeleted' : boolean,
  'deleteReason' : string,
  'deletedAt' : [] | [Time],
}
export interface OrderItem {
  'rate' : number,
  'unit' : string,
  'productId' : string,
  'productName' : string,
  'quantity' : number,
  'amount' : number,
}
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export interface Payment {
  'id' : string,
  'paymentMethod' : PaymentMethod,
  'referenceNumber' : string,
  'storeNumber' : string,
  'recordedAt' : Time,
  'notes' : string,
  'companyName' : string,
  'customerId' : string,
  'amount' : number,
}
export type PaymentMethod = { 'cash' : null } |
  { 'cheque' : null } |
  { 'online' : null };
export interface Product {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'rate' : number,
  'unit' : string,
  'isActive' : boolean,
  'imageUrl' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'customerId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[Customer], undefined>,
  'addOrder' : ActorMethod<[Order], undefined>,
  'addPayment' : ActorMethod<[Payment], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkImportProducts' : ActorMethod<[Array<Product>], undefined>,
  'bulkToggleProducts' : ActorMethod<[boolean], undefined>,
  'deleteCustomer' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'editCustomer' : ActorMethod<[string, Customer], undefined>,
  'editProduct' : ActorMethod<[string, Product], undefined>,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyProfile' : ActorMethod<[], [] | [CompanyProfile]>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getOrdersByCustomer' : ActorMethod<[string], Array<Order>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getPaymentsByCustomer' : ActorMethod<[string], Array<Payment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleCustomerState' : ActorMethod<[string], undefined>,
  'toggleProductState' : ActorMethod<[string], undefined>,
  'updateCompanyProfile' : ActorMethod<[CompanyProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];