/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: string;
    name: string;
    createdAt: Time;
    rate: number;
    unit: string;
    isActive: boolean;
    imageUrl?: ExternalBlob;
}
export interface CompanyProfile {
    bankAccountNumber: string;
    contact: string;
    adminPasswordHash: string;
    ifscCode: string;
    gstNumber: string;
    email: string;
    bankName: string;
    appVersion: string;
    logoUrl?: ExternalBlob;
    adminUserId: string;
    signatureUrl?: ExternalBlob;
    address: string;
    upiQrImageUrl?: ExternalBlob;
    upiId: string;
    companyName: string;
    bankAccountName: string;
    branchName: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface OrderItem {
    rate: number;
    unit: string;
    productId: string;
    productName: string;
    quantity: number;
    amount: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Payment {
    id: string;
    paymentMethod: PaymentMethod;
    referenceNumber: string;
    storeNumber: string;
    recordedAt: Time;
    notes: string;
    companyName: string;
    customerId: string;
    amount: number;
}
export interface DashboardStats {
    totalProducts: bigint;
    totalOrders: bigint;
    todayRevenue: number;
    totalRevenue: number;
    totalCustomers: bigint;
    todayOrders: bigint;
}
export interface Order {
    id: string;
    status: OrderStatus;
    deliveredAt?: Time;
    storeNumber: string;
    createdAt: Time;
    invoiceNumber: string;
    totalAmount: number;
    address: string;
    companyName: string;
    customerId: string;
    items: Array<OrderItem>;
}
export interface Customer {
    id: string;
    customerName: string;
    storeNumber: string;
    gstNumber: string;
    userId?: string;
    createdAt: Time;
    isActive: boolean;
    email: string;
    address: string;
    companyName: string;
    passwordHash: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
    customerId?: string;
}
export enum OrderStatus {
    pending = "pending",
    delivered = "delivered",
    accepted = "accepted"
}
export enum PaymentMethod {
    cash = "cash",
    cheque = "cheque",
    online = "online"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomer(customer: Customer): Promise<void>;
    addOrder(order: Order): Promise<void>;
    addPayment(payment: Payment): Promise<void>;
    addProduct(product: Product): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkImportProducts(productList: Array<Product>): Promise<void>;
    bulkToggleProducts(isActive: boolean): Promise<void>;
    deleteCustomer(storeNumber: string): Promise<void>;
    deleteProduct(productId: string): Promise<void>;
    editCustomer(storeNumber: string, customer: Customer): Promise<void>;
    editProduct(productId: string, product: Product): Promise<void>;
    getActiveProducts(): Promise<Array<Product>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllProducts(): Promise<Array<Product>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanyProfile(): Promise<CompanyProfile | null>;
    getCustomers(): Promise<Array<Customer>>;
    getDashboardStats(): Promise<DashboardStats>;
    getOrdersByCustomer(customerId: string): Promise<Array<Order>>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<Order>>;
    getPaymentsByCustomer(customerId: string): Promise<Array<Payment>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleCustomerState(storeNumber: string): Promise<void>;
    toggleProductState(productId: string): Promise<void>;
    updateCompanyProfile(profile: CompanyProfile): Promise<void>;
    updateOrderStatus(orderId: string, newStatus: OrderStatus): Promise<void>;
}
import type { CompanyProfile as _CompanyProfile, Customer as _Customer, ExternalBlob as _ExternalBlob, Order as _Order, OrderItem as _OrderItem, OrderStatus as _OrderStatus, Payment as _Payment, PaymentMethod as _PaymentMethod, Product as _Product, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomer(arg0: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(to_candid_Customer_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(to_candid_Customer_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrder(to_candid_Order_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrder(to_candid_Order_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPayment(arg0: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(to_candid_Payment_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(to_candid_Payment_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_Product_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_Product_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkImportProducts(arg0: Array<Product>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportProducts(await to_candid_vec_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportProducts(await to_candid_vec_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bulkToggleProducts(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkToggleProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkToggleProducts(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async editCustomer(arg0: string, arg1: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCustomer(arg0, to_candid_Customer_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCustomer(arg0, to_candid_Customer_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async editProduct(arg0: string, arg1: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editProduct(arg0, await to_candid_Product_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editProduct(arg0, await to_candid_Product_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getActiveProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveProducts();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveProducts();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyProfile(): Promise<CompanyProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getOrdersByCustomer(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByCustomer(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByCustomer(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentsByCustomer(arg0: string): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByCustomer(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByCustomer(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleCustomerState(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCustomerState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCustomerState(arg0);
            return result;
        }
    }
    async toggleProductState(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleProductState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleProductState(arg0);
            return result;
        }
    }
    async updateCompanyProfile(arg0: CompanyProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompanyProfile(await to_candid_CompanyProfile_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompanyProfile(await to_candid_CompanyProfile_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_CompanyProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompanyProfile): Promise<CompanyProfile> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_OrderStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanyProfile]): Promise<CompanyProfile | null> {
    return value.length === 0 ? null : await from_candid_CompanyProfile_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: _Time;
    rate: number;
    unit: string;
    isActive: boolean;
    imageUrl: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    name: string;
    createdAt: Time;
    rate: number;
    unit: string;
    isActive: boolean;
    imageUrl?: ExternalBlob;
}> {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        rate: value.rate,
        unit: value.unit,
        isActive: value.isActive,
        imageUrl: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.imageUrl))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    deliveredAt: [] | [_Time];
    storeNumber: string;
    createdAt: _Time;
    invoiceNumber: string;
    totalAmount: number;
    address: string;
    companyName: string;
    customerId: string;
    items: Array<_OrderItem>;
}): {
    id: string;
    status: OrderStatus;
    deliveredAt?: Time;
    storeNumber: string;
    createdAt: Time;
    invoiceNumber: string;
    totalAmount: number;
    address: string;
    companyName: string;
    customerId: string;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n32(_uploadFile, _downloadFile, value.status),
        deliveredAt: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.deliveredAt)),
        storeNumber: value.storeNumber,
        createdAt: value.createdAt,
        invoiceNumber: value.invoiceNumber,
        totalAmount: value.totalAmount,
        address: value.address,
        companyName: value.companyName,
        customerId: value.customerId,
        items: value.items
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    paymentMethod: _PaymentMethod;
    referenceNumber: string;
    storeNumber: string;
    recordedAt: _Time;
    notes: string;
    companyName: string;
    customerId: string;
    amount: number;
}): {
    id: string;
    paymentMethod: PaymentMethod;
    referenceNumber: string;
    storeNumber: string;
    recordedAt: Time;
    notes: string;
    companyName: string;
    customerId: string;
    amount: number;
} {
    return {
        id: value.id,
        paymentMethod: from_candid_PaymentMethod_n38(_uploadFile, _downloadFile, value.paymentMethod),
        referenceNumber: value.referenceNumber,
        storeNumber: value.storeNumber,
        recordedAt: value.recordedAt,
        notes: value.notes,
        companyName: value.companyName,
        customerId: value.customerId,
        amount: value.amount
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    customerId: [] | [string];
}): {
    name: string;
    role: string;
    customerId?: string;
} {
    return {
        name: value.name,
        role: value.role,
        customerId: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.customerId))
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankAccountNumber: string;
    contact: string;
    adminPasswordHash: string;
    ifscCode: string;
    gstNumber: string;
    email: string;
    bankName: string;
    appVersion: string;
    logoUrl: [] | [_ExternalBlob];
    adminUserId: string;
    signatureUrl: [] | [_ExternalBlob];
    address: string;
    upiQrImageUrl: [] | [_ExternalBlob];
    upiId: string;
    companyName: string;
    bankAccountName: string;
    branchName: string;
}): Promise<{
    bankAccountNumber: string;
    contact: string;
    adminPasswordHash: string;
    ifscCode: string;
    gstNumber: string;
    email: string;
    bankName: string;
    appVersion: string;
    logoUrl?: ExternalBlob;
    adminUserId: string;
    signatureUrl?: ExternalBlob;
    address: string;
    upiQrImageUrl?: ExternalBlob;
    upiId: string;
    companyName: string;
    bankAccountName: string;
    branchName: string;
}> {
    return {
        bankAccountNumber: value.bankAccountNumber,
        contact: value.contact,
        adminPasswordHash: value.adminPasswordHash,
        ifscCode: value.ifscCode,
        gstNumber: value.gstNumber,
        email: value.email,
        bankName: value.bankName,
        appVersion: value.appVersion,
        logoUrl: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.logoUrl)),
        adminUserId: value.adminUserId,
        signatureUrl: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.signatureUrl)),
        address: value.address,
        upiQrImageUrl: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.upiQrImageUrl)),
        upiId: value.upiId,
        companyName: value.companyName,
        bankAccountName: value.bankAccountName,
        branchName: value.branchName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    storeNumber: string;
    gstNumber: string;
    userId: [] | [string];
    createdAt: _Time;
    isActive: boolean;
    email: string;
    address: string;
    companyName: string;
    passwordHash: string;
    phone: string;
}): {
    id: string;
    customerName: string;
    storeNumber: string;
    gstNumber: string;
    userId?: string;
    createdAt: Time;
    isActive: boolean;
    email: string;
    address: string;
    companyName: string;
    passwordHash: string;
    phone: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        storeNumber: value.storeNumber,
        gstNumber: value.gstNumber,
        userId: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.userId)),
        createdAt: value.createdAt,
        isActive: value.isActive,
        email: value.email,
        address: value.address,
        companyName: value.companyName,
        passwordHash: value.passwordHash,
        phone: value.phone
    };
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    delivered: null;
} | {
    accepted: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "accepted" in value ? OrderStatus.accepted : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    cheque: null;
} | {
    online: null;
}): PaymentMethod {
    return "cash" in value ? PaymentMethod.cash : "cheque" in value ? PaymentMethod.cheque : "online" in value ? PaymentMethod.online : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n25(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n50(_uploadFile, _downloadFile, x));
}
async function to_candid_CompanyProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompanyProfile): Promise<_CompanyProfile> {
    return await to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_Customer_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Customer): _Customer {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_OrderStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Order_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Payment_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Payment): _Payment {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_Product_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: OrderStatus;
    deliveredAt?: Time;
    storeNumber: string;
    createdAt: Time;
    invoiceNumber: string;
    totalAmount: number;
    address: string;
    companyName: string;
    customerId: string;
    items: Array<OrderItem>;
}): {
    id: string;
    status: _OrderStatus;
    deliveredAt: [] | [_Time];
    storeNumber: string;
    createdAt: _Time;
    invoiceNumber: string;
    totalAmount: number;
    address: string;
    companyName: string;
    customerId: string;
    items: Array<_OrderItem>;
} {
    return {
        id: value.id,
        status: to_candid_OrderStatus_n12(_uploadFile, _downloadFile, value.status),
        deliveredAt: value.deliveredAt ? candid_some(value.deliveredAt) : candid_none(),
        storeNumber: value.storeNumber,
        createdAt: value.createdAt,
        invoiceNumber: value.invoiceNumber,
        totalAmount: value.totalAmount,
        address: value.address,
        companyName: value.companyName,
        customerId: value.customerId,
        items: value.items
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    paymentMethod: PaymentMethod;
    referenceNumber: string;
    storeNumber: string;
    recordedAt: Time;
    notes: string;
    companyName: string;
    customerId: string;
    amount: number;
}): {
    id: string;
    paymentMethod: _PaymentMethod;
    referenceNumber: string;
    storeNumber: string;
    recordedAt: _Time;
    notes: string;
    companyName: string;
    customerId: string;
    amount: number;
} {
    return {
        id: value.id,
        paymentMethod: to_candid_PaymentMethod_n16(_uploadFile, _downloadFile, value.paymentMethod),
        referenceNumber: value.referenceNumber,
        storeNumber: value.storeNumber,
        recordedAt: value.recordedAt,
        notes: value.notes,
        companyName: value.companyName,
        customerId: value.customerId,
        amount: value.amount
    };
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: Time;
    rate: number;
    unit: string;
    isActive: boolean;
    imageUrl?: ExternalBlob;
}): Promise<{
    id: string;
    name: string;
    createdAt: _Time;
    rate: number;
    unit: string;
    isActive: boolean;
    imageUrl: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        rate: value.rate,
        unit: value.unit,
        isActive: value.isActive,
        imageUrl: value.imageUrl ? candid_some(await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.imageUrl)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    customerId?: string;
}): {
    name: string;
    role: string;
    customerId: [] | [string];
} {
    return {
        name: value.name,
        role: value.role,
        customerId: value.customerId ? candid_some(value.customerId) : candid_none()
    };
}
async function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankAccountNumber: string;
    contact: string;
    adminPasswordHash: string;
    ifscCode: string;
    gstNumber: string;
    email: string;
    bankName: string;
    appVersion: string;
    logoUrl?: ExternalBlob;
    adminUserId: string;
    signatureUrl?: ExternalBlob;
    address: string;
    upiQrImageUrl?: ExternalBlob;
    upiId: string;
    companyName: string;
    bankAccountName: string;
    branchName: string;
}): Promise<{
    bankAccountNumber: string;
    contact: string;
    adminPasswordHash: string;
    ifscCode: string;
    gstNumber: string;
    email: string;
    bankName: string;
    appVersion: string;
    logoUrl: [] | [_ExternalBlob];
    adminUserId: string;
    signatureUrl: [] | [_ExternalBlob];
    address: string;
    upiQrImageUrl: [] | [_ExternalBlob];
    upiId: string;
    companyName: string;
    bankAccountName: string;
    branchName: string;
}> {
    return {
        bankAccountNumber: value.bankAccountNumber,
        contact: value.contact,
        adminPasswordHash: value.adminPasswordHash,
        ifscCode: value.ifscCode,
        gstNumber: value.gstNumber,
        email: value.email,
        bankName: value.bankName,
        appVersion: value.appVersion,
        logoUrl: value.logoUrl ? candid_some(await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.logoUrl)) : candid_none(),
        adminUserId: value.adminUserId,
        signatureUrl: value.signatureUrl ? candid_some(await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.signatureUrl)) : candid_none(),
        address: value.address,
        upiQrImageUrl: value.upiQrImageUrl ? candid_some(await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.upiQrImageUrl)) : candid_none(),
        upiId: value.upiId,
        companyName: value.companyName,
        bankAccountName: value.bankAccountName,
        branchName: value.branchName
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    storeNumber: string;
    gstNumber: string;
    userId?: string;
    createdAt: Time;
    isActive: boolean;
    email: string;
    address: string;
    companyName: string;
    passwordHash: string;
    phone: string;
}): {
    id: string;
    customerName: string;
    storeNumber: string;
    gstNumber: string;
    userId: [] | [string];
    createdAt: _Time;
    isActive: boolean;
    email: string;
    address: string;
    companyName: string;
    passwordHash: string;
    phone: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        storeNumber: value.storeNumber,
        gstNumber: value.gstNumber,
        userId: value.userId ? candid_some(value.userId) : candid_none(),
        createdAt: value.createdAt,
        isActive: value.isActive,
        email: value.email,
        address: value.address,
        companyName: value.companyName,
        passwordHash: value.passwordHash,
        phone: value.phone
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    delivered: null;
} | {
    accepted: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cash: null;
} | {
    cheque: null;
} | {
    online: null;
} {
    return value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.cheque ? {
        cheque: null
    } : value == PaymentMethod.online ? {
        online: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Product>): Promise<Array<_Product>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Product_n18(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
