import { OrderStatus, PaymentMethod } from "./backend.d";
import type {
  CompanyProfile,
  Customer,
  DashboardStats,
  Order,
  Payment,
  Product,
} from "./backend.d";

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Basmati Rice (Premium)",
    unit: "Kgs",
    rate: 85,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p2",
    name: "Toor Dal",
    unit: "Kgs",
    rate: 130,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p3",
    name: "Chana Dal",
    unit: "Kgs",
    rate: 115,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p4",
    name: "Moong Dal",
    unit: "Kgs",
    rate: 125,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p5",
    name: "Urad Dal",
    unit: "Kgs",
    rate: 140,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p6",
    name: "Masoor Dal",
    unit: "Kgs",
    rate: 110,
    isActive: false,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p7",
    name: "Wheat Flour (Atta)",
    unit: "Kgs",
    rate: 42,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p8",
    name: "Maida",
    unit: "Kgs",
    rate: 38,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p9",
    name: "Besan (Gram Flour)",
    unit: "Kgs",
    rate: 75,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p10",
    name: "Semolina (Sooji)",
    unit: "Kgs",
    rate: 45,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p11",
    name: "Sunflower Oil",
    unit: "Each",
    rate: 155,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p12",
    name: "Groundnut Oil",
    unit: "Each",
    rate: 180,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p13",
    name: "Mustard Oil",
    unit: "Each",
    rate: 165,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p14",
    name: "Coconut Oil",
    unit: "Each",
    rate: 210,
    isActive: false,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p15",
    name: "Refined Oil (5L)",
    unit: "Each",
    rate: 720,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p16",
    name: "Sugar",
    unit: "Kgs",
    rate: 48,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p17",
    name: "Salt (Iodized)",
    unit: "Kgs",
    rate: 18,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p18",
    name: "Turmeric Powder",
    unit: "Kgs",
    rate: 220,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p19",
    name: "Red Chilli Powder",
    unit: "Kgs",
    rate: 280,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p20",
    name: "Coriander Powder",
    unit: "Kgs",
    rate: 180,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p21",
    name: "Cumin Seeds",
    unit: "Kgs",
    rate: 420,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p22",
    name: "Mustard Seeds",
    unit: "Kgs",
    rate: 110,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p23",
    name: "Black Pepper",
    unit: "Kgs",
    rate: 680,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p24",
    name: "Cardamom",
    unit: "Kgs",
    rate: 2200,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p25",
    name: "Cloves",
    unit: "Kgs",
    rate: 1800,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p26",
    name: "Cinnamon Sticks",
    unit: "Kgs",
    rate: 850,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p27",
    name: "Bay Leaves",
    unit: "Kgs",
    rate: 250,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p28",
    name: "Fenugreek Seeds",
    unit: "Kgs",
    rate: 95,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p29",
    name: "Asafoetida (Hing)",
    unit: "Kgs",
    rate: 1200,
    isActive: false,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p30",
    name: "Garam Masala",
    unit: "Kgs",
    rate: 650,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p31",
    name: "Tea Powder (CTC)",
    unit: "Kgs",
    rate: 380,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p32",
    name: "Coffee Powder",
    unit: "Kgs",
    rate: 520,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p33",
    name: "Milk Powder",
    unit: "Kgs",
    rate: 340,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p34",
    name: "Ghee (1L)",
    unit: "Each",
    rate: 580,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p35",
    name: "Butter (500g)",
    unit: "Each",
    rate: 260,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p36",
    name: "Paneer (500g)",
    unit: "Each",
    rate: 220,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p37",
    name: "Dahi / Curd (500g)",
    unit: "Each",
    rate: 55,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p38",
    name: "Vermicelli",
    unit: "Kgs",
    rate: 65,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p39",
    name: "Poha (Flattened Rice)",
    unit: "Kgs",
    rate: 55,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p40",
    name: "Sabudana (Sago)",
    unit: "Kgs",
    rate: 95,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p41",
    name: "Peanuts (Raw)",
    unit: "Kgs",
    rate: 120,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p42",
    name: "Cashew Nuts",
    unit: "Kgs",
    rate: 880,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p43",
    name: "Almonds",
    unit: "Kgs",
    rate: 720,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p44",
    name: "Raisins",
    unit: "Kgs",
    rate: 280,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p45",
    name: "Dates",
    unit: "Kgs",
    rate: 195,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p46",
    name: "Tamarind",
    unit: "Kgs",
    rate: 75,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p47",
    name: "Jaggery",
    unit: "Kgs",
    rate: 65,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p48",
    name: "Honey (500g)",
    unit: "Each",
    rate: 220,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p49",
    name: "Vinegar",
    unit: "Each",
    rate: 45,
    isActive: false,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p50",
    name: "Tomato Sauce (1kg)",
    unit: "Each",
    rate: 125,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p51",
    name: "Soya Sauce",
    unit: "Each",
    rate: 85,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p52",
    name: "Green Chilli Sauce",
    unit: "Each",
    rate: 70,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p53",
    name: "Papad (Plain)",
    unit: "Kgs",
    rate: 180,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p54",
    name: "Pickle (Mixed 500g)",
    unit: "Each",
    rate: 95,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p55",
    name: "Jam (500g)",
    unit: "Each",
    rate: 110,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p56",
    name: "Biscuits (Parle-G)",
    unit: "Each",
    rate: 10,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p57",
    name: "Namkeen Mix",
    unit: "Kgs",
    rate: 220,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p58",
    name: "Chakki Fresh Atta (10kg)",
    unit: "Each",
    rate: 380,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p59",
    name: "Pasta (500g)",
    unit: "Each",
    rate: 55,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p60",
    name: "Noodles (Maggi)",
    unit: "Each",
    rate: 14,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p61",
    name: "Oats (1kg)",
    unit: "Each",
    rate: 145,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p62",
    name: "Corn Flakes (500g)",
    unit: "Each",
    rate: 120,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p63",
    name: "Muesli (400g)",
    unit: "Each",
    rate: 185,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p64",
    name: "Washing Powder (1kg)",
    unit: "Each",
    rate: 85,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p65",
    name: "Dish Wash Bar",
    unit: "Each",
    rate: 35,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p66",
    name: "Floor Cleaner (1L)",
    unit: "Each",
    rate: 95,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p67",
    name: "Toilet Cleaner (500ml)",
    unit: "Each",
    rate: 65,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p68",
    name: "Soap Bar (Lifebuoy)",
    unit: "Each",
    rate: 35,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p69",
    name: "Shampoo (200ml)",
    unit: "Each",
    rate: 145,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p70",
    name: "Toothpaste (150g)",
    unit: "Each",
    rate: 75,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p71",
    name: "Mineral Water (1L)",
    unit: "Each",
    rate: 20,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p72",
    name: "Cold Drink (Coke 2L)",
    unit: "Each",
    rate: 95,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p73",
    name: "Fruit Juice (1L)",
    unit: "Each",
    rate: 120,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p74",
    name: "Potato Chips (50g)",
    unit: "Each",
    rate: 20,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p75",
    name: "Tomatoes (Fresh)",
    unit: "Kgs",
    rate: 35,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p76",
    name: "Onions",
    unit: "Kgs",
    rate: 30,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p77",
    name: "Potatoes",
    unit: "Kgs",
    rate: 28,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p78",
    name: "Ginger",
    unit: "Kgs",
    rate: 120,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p79",
    name: "Garlic",
    unit: "Kgs",
    rate: 95,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p80",
    name: "Green Peas (Frozen)",
    unit: "Kgs",
    rate: 85,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p81",
    name: "Corn (Baby)",
    unit: "Kgs",
    rate: 180,
    isActive: false,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p82",
    name: "Cauliflower",
    unit: "Each",
    rate: 35,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p83",
    name: "Cabbage",
    unit: "Each",
    rate: 25,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p84",
    name: "Bhindi (Okra)",
    unit: "Kgs",
    rate: 45,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p85",
    name: "Brinjal",
    unit: "Kgs",
    rate: 35,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p86",
    name: "Capsicum",
    unit: "Kgs",
    rate: 65,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p87",
    name: "Lemon",
    unit: "Kgs",
    rate: 80,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p88",
    name: "Coconut (Fresh)",
    unit: "Each",
    rate: 35,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p89",
    name: "Banana (Dozen)",
    unit: "Each",
    rate: 45,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p90",
    name: "Apple (1kg)",
    unit: "Kgs",
    rate: 180,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p91",
    name: "Mango (Alphonso)",
    unit: "Kgs",
    rate: 350,
    isActive: false,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p92",
    name: "Grapes",
    unit: "Kgs",
    rate: 95,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p93",
    name: "Amul Butter (500g)",
    unit: "Each",
    rate: 275,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p94",
    name: "Cheese Slice (200g)",
    unit: "Each",
    rate: 185,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p95",
    name: "Egg (Dozen)",
    unit: "Each",
    rate: 85,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p96",
    name: "Brown Bread",
    unit: "Each",
    rate: 55,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p97",
    name: "White Bread",
    unit: "Each",
    rate: 45,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p98",
    name: "Pav Bread (8pcs)",
    unit: "Each",
    rate: 35,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p99",
    name: "Saffron (1g)",
    unit: "Each",
    rate: 180,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p100",
    name: "Dry Coconut (Copra)",
    unit: "Kgs",
    rate: 240,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p101",
    name: "Sesame Seeds",
    unit: "Kgs",
    rate: 180,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p102",
    name: "Flax Seeds",
    unit: "Kgs",
    rate: 220,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p103",
    name: "Chia Seeds",
    unit: "Kgs",
    rate: 680,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p104",
    name: "Rajma (Kidney Beans)",
    unit: "Kgs",
    rate: 145,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "p105",
    name: "Kabuli Chana",
    unit: "Kgs",
    rate: 165,
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    storeNumber: "STR001",
    customerName: "Ramesh Patel",
    phone: "9876543210",
    companyName: "Patel Kirana Store",
    address: "12, Gandhi Nagar, Mumbai - 400001",
    gstNumber: "27AABCP1234A1Z5",
    email: "ramesh@patelkirana.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c2",
    storeNumber: "STR002",
    customerName: "Suresh Kumar",
    phone: "9845621370",
    companyName: "Kumar General Store",
    address: "45, MG Road, Pune - 411001",
    gstNumber: "27AABCK5678B2Z6",
    email: "suresh@kumarstore.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c3",
    storeNumber: "STR003",
    customerName: "Priya Sharma",
    phone: "9712345678",
    companyName: "Sharma Provisions",
    address: "78, Station Road, Nashik - 422001",
    gstNumber: "27AABCS9012C3Z7",
    email: "priya@sharmaprovisions.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c4",
    storeNumber: "STR004",
    customerName: "Vijay Mehta",
    phone: "9632587410",
    companyName: "Mehta Super Market",
    address: "23, Ring Road, Surat - 395001",
    gstNumber: "24AABCM3456D4Z8",
    email: "vijay@mehtamarket.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c5",
    storeNumber: "STR005",
    customerName: "Anita Desai",
    phone: "9087654321",
    companyName: "Desai Daily Needs",
    address: "56, Residency Road, Bangalore - 560001",
    gstNumber: "29AABCD7890E5Z9",
    email: "anita@desaidaily.com",
    passwordHash: "pass123",
    isActive: false,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c6",
    storeNumber: "STR006",
    customerName: "Manoj Joshi",
    phone: "9512347896",
    companyName: "Joshi Family Store",
    address: "90, Civil Lines, Nagpur - 440001",
    gstNumber: "27AABCJ1234F6Z0",
    email: "manoj@joshistore.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c7",
    storeNumber: "STR007",
    customerName: "Kavita Singh",
    phone: "9823456701",
    companyName: "Singh Superstore",
    address: "34, Hazratganj, Lucknow - 226001",
    gstNumber: "09AABCS5678G7Z1",
    email: "kavita@singhstore.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c8",
    storeNumber: "STR008",
    customerName: "Rajiv Verma",
    phone: "9654321870",
    companyName: "Verma Wholesale",
    address: "67, Karol Bagh, Delhi - 110005",
    gstNumber: "07AABCV9012H8Z2",
    email: "rajiv@vermawholesale.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c9",
    storeNumber: "STR009",
    customerName: "Deepa Nair",
    phone: "9741852963",
    companyName: "Nair Departmental",
    address: "12, MG Road, Kochi - 682001",
    gstNumber: "32AABCN3456I9Z3",
    email: "deepa@nairdept.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c10",
    storeNumber: "STR010",
    customerName: "Arjun Reddy",
    phone: "9369258147",
    companyName: "Reddy Provision Store",
    address: "89, Banjara Hills, Hyderabad - 500034",
    gstNumber: "36AABCR7890J0Z4",
    email: "arjun@reddystore.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c11",
    storeNumber: "STR011",
    customerName: "Sunita Gupta",
    phone: "9258147036",
    companyName: "Gupta Kirana",
    address: "45, Ashok Nagar, Bhopal - 462001",
    gstNumber: "23AABCG1234K1Z5",
    email: "sunita@guptakirana.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c12",
    storeNumber: "STR012",
    customerName: "Rakesh Tiwari",
    phone: "9147036925",
    companyName: "Tiwari General Stores",
    address: "78, Sigra, Varanasi - 221001",
    gstNumber: "09AABCT5678L2Z6",
    email: "rakesh@tiwaristores.com",
    passwordHash: "pass123",
    isActive: false,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c13",
    storeNumber: "STR013",
    customerName: "Neha Agarwal",
    phone: "9036925814",
    companyName: "Agarwal Super Store",
    address: "23, Civil Lines, Allahabad - 211001",
    gstNumber: "09AABCA9012M3Z7",
    email: "neha@agarwalstore.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c14",
    storeNumber: "STR014",
    customerName: "Ashok Pandey",
    phone: "9925814703",
    companyName: "Pandey Provisions",
    address: "56, Gorakhpur Road, Ayodhya - 224001",
    gstNumber: "09AABCP3456N4Z8",
    email: "ashok@pandeyprovisions.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c15",
    storeNumber: "STR015",
    customerName: "Meena Chaudhary",
    phone: "9814703692",
    companyName: "Chaudhary Daily Store",
    address: "34, Station Road, Jaipur - 302001",
    gstNumber: "08AABCC7890O5Z9",
    email: "meena@chaudharydaily.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c16",
    storeNumber: "STR016",
    customerName: "Sanjay Mishra",
    phone: "9703692581",
    companyName: "Mishra Kiryana",
    address: "90, Jhotwara Road, Jaipur - 302012",
    gstNumber: "08AABCM1234P6Z0",
    email: "sanjay@mishrakiryana.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c17",
    storeNumber: "STR017",
    customerName: "Pooja Yadav",
    phone: "9692581470",
    companyName: "Yadav Supermart",
    address: "12, Boring Road, Patna - 800001",
    gstNumber: "10AABCY5678Q7Z1",
    email: "pooja@yadavsupermart.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c18",
    storeNumber: "STR018",
    customerName: "Dinesh Shah",
    phone: "9581470369",
    companyName: "Shah Family Mart",
    address: "45, Navrangpura, Ahmedabad - 380009",
    gstNumber: "24AABCS9012R8Z2",
    email: "dinesh@shahmart.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c19",
    storeNumber: "STR019",
    customerName: "Rekha Pillai",
    phone: "9470369258",
    companyName: "Pillai Nila Stores",
    address: "78, Thiruvananthapuram Rd, Trivandrum - 695001",
    gstNumber: "32AABCP3456S9Z3",
    email: "rekha@pillaistores.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c20",
    storeNumber: "STR020",
    customerName: "Harish Bose",
    phone: "9369258470",
    companyName: "Bose Corner Store",
    address: "23, Park Street, Kolkata - 700016",
    gstNumber: "19AABCB7890T0Z4",
    email: "harish@bosecorner.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c21",
    storeNumber: "STR021",
    customerName: "Lalit Choudhury",
    phone: "9258470369",
    companyName: "Choudhury Provisions",
    address: "56, Fancy Bazar, Guwahati - 781001",
    gstNumber: "18AABCC1234U1Z5",
    email: "lalit@choudhury.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
  {
    id: "c22",
    storeNumber: "STR022",
    customerName: "Shweta Bajaj",
    phone: "9147258036",
    companyName: "Bajaj Trading Co.",
    address: "34, Sadar Bazaar, Nagpur - 440002",
    gstNumber: "27AABCB5678V2Z6",
    email: "shweta@bajajtrading.com",
    passwordHash: "pass123",
    isActive: true,
    createdAt: BigInt(Date.now()),
  },
];

const makeOrder = (
  id: string,
  invNo: string,
  custId: string,
  storeNum: string,
  company: string,
  address: string,
  status: OrderStatus,
  daysAgo: number,
  items: Array<{
    productId: string;
    productName: string;
    unit: string;
    qty: number;
    rate: number;
  }>,
) => {
  const itemsWithAmount = items.map((i) => ({
    ...i,
    quantity: i.qty,
    amount: i.qty * i.rate,
  }));
  const total = itemsWithAmount.reduce((s, i) => s + i.amount, 0);
  const createdAt = BigInt(Date.now() - daysAgo * 86400000);
  const deliveredAt =
    status === OrderStatus.delivered
      ? BigInt(Date.now() - (daysAgo - 1) * 86400000)
      : undefined;
  return {
    id,
    invoiceNumber: invNo,
    customerId: custId,
    storeNumber: storeNum,
    companyName: company,
    address,
    status,
    totalAmount: total,
    items: itemsWithAmount.map((i) => ({
      productId: i.productId,
      productName: i.productName,
      unit: i.unit,
      quantity: i.quantity,
      rate: i.rate,
      amount: i.amount,
    })),
    createdAt,
    deliveredAt,
    isDeleted: false,
    deleteReason: "",
  };
};

export const mockOrders: Order[] = [
  makeOrder(
    "o1",
    "GS/2024/001",
    "c1",
    "STR001",
    "Patel Kirana Store",
    "12, Gandhi Nagar, Mumbai",
    OrderStatus.delivered,
    30,
    [
      {
        productId: "p1",
        productName: "Basmati Rice",
        unit: "Kgs",
        qty: 50,
        rate: 85,
      },
      {
        productId: "p16",
        productName: "Sugar",
        unit: "Kgs",
        qty: 25,
        rate: 48,
      },
    ],
  ),
  makeOrder(
    "o2",
    "GS/2024/002",
    "c2",
    "STR002",
    "Kumar General Store",
    "45, MG Road, Pune",
    OrderStatus.delivered,
    28,
    [
      {
        productId: "p7",
        productName: "Wheat Flour",
        unit: "Kgs",
        qty: 100,
        rate: 42,
      },
      {
        productId: "p11",
        productName: "Sunflower Oil",
        unit: "Each",
        qty: 10,
        rate: 155,
      },
    ],
  ),
  makeOrder(
    "o3",
    "GS/2024/003",
    "c3",
    "STR003",
    "Sharma Provisions",
    "78, Station Road, Nashik",
    OrderStatus.accepted,
    5,
    [
      {
        productId: "p2",
        productName: "Toor Dal",
        unit: "Kgs",
        qty: 30,
        rate: 130,
      },
      {
        productId: "p3",
        productName: "Chana Dal",
        unit: "Kgs",
        qty: 20,
        rate: 115,
      },
    ],
  ),
  makeOrder(
    "o4",
    "GS/2024/004",
    "c4",
    "STR004",
    "Mehta Super Market",
    "23, Ring Road, Surat",
    OrderStatus.pending,
    1,
    [
      {
        productId: "p34",
        productName: "Ghee",
        unit: "Each",
        qty: 20,
        rate: 580,
      },
      {
        productId: "p16",
        productName: "Sugar",
        unit: "Kgs",
        qty: 50,
        rate: 48,
      },
    ],
  ),
  makeOrder(
    "o5",
    "GS/2024/005",
    "c6",
    "STR006",
    "Joshi Family Store",
    "90, Civil Lines, Nagpur",
    OrderStatus.delivered,
    25,
    [
      {
        productId: "p18",
        productName: "Turmeric Powder",
        unit: "Kgs",
        qty: 10,
        rate: 220,
      },
      {
        productId: "p19",
        productName: "Red Chilli Powder",
        unit: "Kgs",
        qty: 10,
        rate: 280,
      },
    ],
  ),
  makeOrder(
    "o6",
    "GS/2024/006",
    "c7",
    "STR007",
    "Singh Superstore",
    "34, Hazratganj, Lucknow",
    OrderStatus.accepted,
    3,
    [
      {
        productId: "p1",
        productName: "Basmati Rice",
        unit: "Kgs",
        qty: 100,
        rate: 85,
      },
      {
        productId: "p4",
        productName: "Moong Dal",
        unit: "Kgs",
        qty: 40,
        rate: 125,
      },
    ],
  ),
  makeOrder(
    "o7",
    "GS/2024/007",
    "c8",
    "STR008",
    "Verma Wholesale",
    "67, Karol Bagh, Delhi",
    OrderStatus.pending,
    0,
    [
      {
        productId: "p64",
        productName: "Washing Powder",
        unit: "Each",
        qty: 50,
        rate: 85,
      },
      {
        productId: "p65",
        productName: "Dish Wash Bar",
        unit: "Each",
        qty: 100,
        rate: 35,
      },
    ],
  ),
  makeOrder(
    "o8",
    "GS/2024/008",
    "c9",
    "STR009",
    "Nair Departmental",
    "12, MG Road, Kochi",
    OrderStatus.delivered,
    20,
    [
      {
        productId: "p88",
        productName: "Coconut",
        unit: "Each",
        qty: 200,
        rate: 35,
      },
      {
        productId: "p87",
        productName: "Lemon",
        unit: "Kgs",
        qty: 20,
        rate: 80,
      },
    ],
  ),
  makeOrder(
    "o9",
    "GS/2024/009",
    "c10",
    "STR010",
    "Reddy Provision Store",
    "89, Banjara Hills, Hyderabad",
    OrderStatus.delivered,
    15,
    [
      {
        productId: "p2",
        productName: "Toor Dal",
        unit: "Kgs",
        qty: 50,
        rate: 130,
      },
      {
        productId: "p5",
        productName: "Urad Dal",
        unit: "Kgs",
        qty: 30,
        rate: 140,
      },
    ],
  ),
  makeOrder(
    "o10",
    "GS/2024/010",
    "c11",
    "STR011",
    "Gupta Kirana",
    "45, Ashok Nagar, Bhopal",
    OrderStatus.pending,
    0,
    [
      {
        productId: "p31",
        productName: "Tea Powder",
        unit: "Kgs",
        qty: 20,
        rate: 380,
      },
      {
        productId: "p16",
        productName: "Sugar",
        unit: "Kgs",
        qty: 30,
        rate: 48,
      },
    ],
  ),
  makeOrder(
    "o11",
    "GS/2024/011",
    "c13",
    "STR013",
    "Agarwal Super Store",
    "23, Civil Lines, Allahabad",
    OrderStatus.accepted,
    4,
    [
      {
        productId: "p7",
        productName: "Wheat Flour",
        unit: "Kgs",
        qty: 200,
        rate: 42,
      },
      { productId: "p8", productName: "Maida", unit: "Kgs", qty: 50, rate: 38 },
    ],
  ),
  makeOrder(
    "o12",
    "GS/2024/012",
    "c14",
    "STR014",
    "Pandey Provisions",
    "56, Gorakhpur Road, Ayodhya",
    OrderStatus.delivered,
    18,
    [
      {
        productId: "p34",
        productName: "Ghee",
        unit: "Each",
        qty: 15,
        rate: 580,
      },
      {
        productId: "p93",
        productName: "Amul Butter",
        unit: "Each",
        qty: 20,
        rate: 275,
      },
    ],
  ),
  makeOrder(
    "o13",
    "GS/2024/013",
    "c15",
    "STR015",
    "Chaudhary Daily Store",
    "34, Station Road, Jaipur",
    OrderStatus.pending,
    1,
    [
      {
        productId: "p41",
        productName: "Peanuts",
        unit: "Kgs",
        qty: 25,
        rate: 120,
      },
      {
        productId: "p47",
        productName: "Jaggery",
        unit: "Kgs",
        qty: 30,
        rate: 65,
      },
    ],
  ),
  makeOrder(
    "o14",
    "GS/2024/014",
    "c16",
    "STR016",
    "Mishra Kiryana",
    "90, Jhotwara Road, Jaipur",
    OrderStatus.delivered,
    12,
    [
      {
        productId: "p1",
        productName: "Basmati Rice",
        unit: "Kgs",
        qty: 80,
        rate: 85,
      },
      {
        productId: "p2",
        productName: "Toor Dal",
        unit: "Kgs",
        qty: 40,
        rate: 130,
      },
    ],
  ),
  makeOrder(
    "o15",
    "GS/2024/015",
    "c17",
    "STR017",
    "Yadav Supermart",
    "12, Boring Road, Patna",
    OrderStatus.accepted,
    2,
    [
      {
        productId: "p11",
        productName: "Sunflower Oil",
        unit: "Each",
        qty: 20,
        rate: 155,
      },
      {
        productId: "p15",
        productName: "Refined Oil 5L",
        unit: "Each",
        qty: 10,
        rate: 720,
      },
    ],
  ),
  makeOrder(
    "o16",
    "GS/2024/016",
    "c18",
    "STR018",
    "Shah Family Mart",
    "45, Navrangpura, Ahmedabad",
    OrderStatus.delivered,
    8,
    [
      {
        productId: "p24",
        productName: "Cardamom",
        unit: "Kgs",
        qty: 5,
        rate: 2200,
      },
      {
        productId: "p21",
        productName: "Cumin Seeds",
        unit: "Kgs",
        qty: 10,
        rate: 420,
      },
    ],
  ),
  makeOrder(
    "o17",
    "GS/2024/017",
    "c19",
    "STR019",
    "Pillai Nila Stores",
    "78, Thiruvananthapuram Rd, Trivandrum",
    OrderStatus.delivered,
    22,
    [
      {
        productId: "p89",
        productName: "Banana Dozen",
        unit: "Each",
        qty: 50,
        rate: 45,
      },
      {
        productId: "p90",
        productName: "Apple",
        unit: "Kgs",
        qty: 30,
        rate: 180,
      },
    ],
  ),
  makeOrder(
    "o18",
    "GS/2024/018",
    "c20",
    "STR020",
    "Bose Corner Store",
    "23, Park Street, Kolkata",
    OrderStatus.pending,
    0,
    [
      {
        productId: "p56",
        productName: "Parle-G Biscuits",
        unit: "Each",
        qty: 200,
        rate: 10,
      },
      {
        productId: "p74",
        productName: "Potato Chips",
        unit: "Each",
        qty: 100,
        rate: 20,
      },
    ],
  ),
  makeOrder(
    "o19",
    "GS/2024/019",
    "c21",
    "STR021",
    "Choudhury Provisions",
    "56, Fancy Bazar, Guwahati",
    OrderStatus.accepted,
    3,
    [
      {
        productId: "p7",
        productName: "Wheat Flour",
        unit: "Kgs",
        qty: 150,
        rate: 42,
      },
      {
        productId: "p16",
        productName: "Sugar",
        unit: "Kgs",
        qty: 100,
        rate: 48,
      },
    ],
  ),
  makeOrder(
    "o20",
    "GS/2024/020",
    "c22",
    "STR022",
    "Bajaj Trading Co.",
    "34, Sadar Bazaar, Nagpur",
    OrderStatus.delivered,
    10,
    [
      {
        productId: "p42",
        productName: "Cashew Nuts",
        unit: "Kgs",
        qty: 10,
        rate: 880,
      },
      {
        productId: "p43",
        productName: "Almonds",
        unit: "Kgs",
        qty: 10,
        rate: 720,
      },
    ],
  ),
  makeOrder(
    "o21",
    "GS/2024/021",
    "c1",
    "STR001",
    "Patel Kirana Store",
    "12, Gandhi Nagar, Mumbai",
    OrderStatus.delivered,
    45,
    [
      {
        productId: "p16",
        productName: "Sugar",
        unit: "Kgs",
        qty: 100,
        rate: 48,
      },
      {
        productId: "p7",
        productName: "Wheat Flour",
        unit: "Kgs",
        qty: 150,
        rate: 42,
      },
    ],
  ),
  makeOrder(
    "o22",
    "GS/2024/022",
    "c2",
    "STR002",
    "Kumar General Store",
    "45, MG Road, Pune",
    OrderStatus.delivered,
    40,
    [
      {
        productId: "p2",
        productName: "Toor Dal",
        unit: "Kgs",
        qty: 60,
        rate: 130,
      },
      {
        productId: "p3",
        productName: "Chana Dal",
        unit: "Kgs",
        qty: 40,
        rate: 115,
      },
    ],
  ),
  makeOrder(
    "o23",
    "GS/2024/023",
    "c3",
    "STR003",
    "Sharma Provisions",
    "78, Station Road, Nashik",
    OrderStatus.delivered,
    35,
    [
      {
        productId: "p18",
        productName: "Turmeric Powder",
        unit: "Kgs",
        qty: 15,
        rate: 220,
      },
      {
        productId: "p19",
        productName: "Red Chilli Powder",
        unit: "Kgs",
        qty: 15,
        rate: 280,
      },
    ],
  ),
  makeOrder(
    "o24",
    "GS/2024/024",
    "c4",
    "STR004",
    "Mehta Super Market",
    "23, Ring Road, Surat",
    OrderStatus.delivered,
    33,
    [
      {
        productId: "p34",
        productName: "Ghee",
        unit: "Each",
        qty: 25,
        rate: 580,
      },
      {
        productId: "p35",
        productName: "Butter",
        unit: "Each",
        qty: 30,
        rate: 260,
      },
    ],
  ),
  makeOrder(
    "o25",
    "GS/2024/025",
    "c5",
    "STR005",
    "Desai Daily Needs",
    "56, Residency Road, Bangalore",
    OrderStatus.delivered,
    50,
    [
      {
        productId: "p64",
        productName: "Washing Powder",
        unit: "Each",
        qty: 30,
        rate: 85,
      },
      {
        productId: "p66",
        productName: "Floor Cleaner",
        unit: "Each",
        qty: 20,
        rate: 95,
      },
    ],
  ),
  makeOrder(
    "o26",
    "GS/2024/026",
    "c6",
    "STR006",
    "Joshi Family Store",
    "90, Civil Lines, Nagpur",
    OrderStatus.delivered,
    27,
    [
      {
        productId: "p1",
        productName: "Basmati Rice",
        unit: "Kgs",
        qty: 75,
        rate: 85,
      },
      {
        productId: "p16",
        productName: "Sugar",
        unit: "Kgs",
        qty: 50,
        rate: 48,
      },
    ],
  ),
  makeOrder(
    "o27",
    "GS/2024/027",
    "c8",
    "STR008",
    "Verma Wholesale",
    "67, Karol Bagh, Delhi",
    OrderStatus.delivered,
    22,
    [
      {
        productId: "p4",
        productName: "Moong Dal",
        unit: "Kgs",
        qty: 80,
        rate: 125,
      },
      {
        productId: "p5",
        productName: "Urad Dal",
        unit: "Kgs",
        qty: 60,
        rate: 140,
      },
    ],
  ),
  makeOrder(
    "o28",
    "GS/2024/028",
    "c9",
    "STR009",
    "Nair Departmental",
    "12, MG Road, Kochi",
    OrderStatus.delivered,
    18,
    [
      {
        productId: "p31",
        productName: "Tea Powder",
        unit: "Kgs",
        qty: 30,
        rate: 380,
      },
      {
        productId: "p32",
        productName: "Coffee Powder",
        unit: "Kgs",
        qty: 10,
        rate: 520,
      },
    ],
  ),
  makeOrder(
    "o29",
    "GS/2024/029",
    "c10",
    "STR010",
    "Reddy Provision Store",
    "89, Banjara Hills, Hyderabad",
    OrderStatus.delivered,
    14,
    [
      {
        productId: "p90",
        productName: "Apple",
        unit: "Kgs",
        qty: 50,
        rate: 180,
      },
      {
        productId: "p92",
        productName: "Grapes",
        unit: "Kgs",
        qty: 30,
        rate: 95,
      },
    ],
  ),
  makeOrder(
    "o30",
    "GS/2024/030",
    "c11",
    "STR011",
    "Gupta Kirana",
    "45, Ashok Nagar, Bhopal",
    OrderStatus.delivered,
    9,
    [
      {
        productId: "p7",
        productName: "Wheat Flour",
        unit: "Kgs",
        qty: 200,
        rate: 42,
      },
      {
        productId: "p8",
        productName: "Maida",
        unit: "Kgs",
        qty: 100,
        rate: 38,
      },
    ],
  ),
  makeOrder(
    "o31",
    "GS/2024/031",
    "c15",
    "STR015",
    "Chaudhary Daily Store",
    "34, Station Road, Jaipur",
    OrderStatus.delivered,
    7,
    [
      {
        productId: "p21",
        productName: "Cumin Seeds",
        unit: "Kgs",
        qty: 20,
        rate: 420,
      },
      {
        productId: "p22",
        productName: "Mustard Seeds",
        unit: "Kgs",
        qty: 15,
        rate: 110,
      },
    ],
  ),
  makeOrder(
    "o32",
    "GS/2024/032",
    "c20",
    "STR020",
    "Bose Corner Store",
    "23, Park Street, Kolkata",
    OrderStatus.delivered,
    5,
    [
      {
        productId: "p48",
        productName: "Honey",
        unit: "Each",
        qty: 25,
        rate: 220,
      },
      {
        productId: "p44",
        productName: "Raisins",
        unit: "Kgs",
        qty: 10,
        rate: 280,
      },
    ],
  ),
];

export const mockPayments: Payment[] = [
  {
    id: "pay1",
    customerId: "c1",
    storeNumber: "STR001",
    companyName: "Patel Kirana Store",
    amount: 10000,
    paymentMethod: PaymentMethod.online,
    referenceNumber: "UTR123456789",
    recordedAt: BigInt(Date.now() - 5 * 86400000),
    notes: "Payment for GS/2024/001",
  },
  {
    id: "pay2",
    customerId: "c2",
    storeNumber: "STR002",
    companyName: "Kumar General Store",
    amount: 7500,
    paymentMethod: PaymentMethod.cheque,
    referenceNumber: "CHQ00123456",
    recordedAt: BigInt(Date.now() - 10 * 86400000),
    notes: "Partial payment",
  },
  {
    id: "pay3",
    customerId: "c3",
    storeNumber: "STR003",
    companyName: "Sharma Provisions",
    amount: 5000,
    paymentMethod: PaymentMethod.cash,
    referenceNumber: "",
    recordedAt: BigInt(Date.now() - 3 * 86400000),
    notes: "Cash payment",
  },
  {
    id: "pay4",
    customerId: "c4",
    storeNumber: "STR004",
    companyName: "Mehta Super Market",
    amount: 15000,
    paymentMethod: PaymentMethod.online,
    referenceNumber: "UTR987654321",
    recordedAt: BigInt(Date.now() - 7 * 86400000),
    notes: "Full settlement",
  },
  {
    id: "pay5",
    customerId: "c8",
    storeNumber: "STR008",
    companyName: "Verma Wholesale",
    amount: 20000,
    paymentMethod: PaymentMethod.cheque,
    referenceNumber: "CHQ00456789",
    recordedAt: BigInt(Date.now() - 2 * 86400000),
    notes: "Monthly payment",
  },
  {
    id: "pay6",
    customerId: "c10",
    storeNumber: "STR010",
    companyName: "Reddy Provision Store",
    amount: 8500,
    paymentMethod: PaymentMethod.cash,
    referenceNumber: "",
    recordedAt: BigInt(Date.now() - 1 * 86400000),
    notes: "",
  },
  {
    id: "pay7",
    customerId: "c15",
    storeNumber: "STR015",
    companyName: "Chaudhary Daily Store",
    amount: 12000,
    paymentMethod: PaymentMethod.online,
    referenceNumber: "UTR567891234",
    recordedAt: BigInt(Date.now() - 15 * 86400000),
    notes: "",
  },
];

export const mockCompanyProfile: CompanyProfile = {
  companyName: "Ganesh Suppliers",
  gstNumber: "27AABCG1234A1Z5",
  contact: "9876543210",
  email: "admin@ganeshsuppliers.com",
  address: "15, Wholesale Market, APMC, Navi Mumbai - 400614, Maharashtra",
  bankAccountNumber: "12345678901234",
  bankAccountName: "Ganesh Suppliers",
  bankName: "State Bank of India",
  ifscCode: "SBIN0001234",
  upiId: "ganeshsuppliers@sbi",
  branchName: "APMC Vashi Branch",
  adminUserId: "admin",
  adminPasswordHash: "admin123",
  appVersion: "v1.0.0",
};

export const mockDashboardStats: DashboardStats = {
  totalOrders: BigInt(32),
  todayOrders: BigInt(3),
  todayRevenue: 47500,
  totalRevenue: 2845600,
  totalCustomers: BigInt(22),
  totalProducts: BigInt(105),
};

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatDate(ts: bigint | number | undefined): string {
  if (!ts) return "-";
  const d = new Date(typeof ts === "bigint" ? Number(ts) : ts);
  return d.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
}

export function formatDateTime(ts: bigint | number | undefined): string {
  if (!ts) return "-";
  const d = new Date(typeof ts === "bigint" ? Number(ts) : ts);
  return d.toLocaleString("en-IN", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}
